# Generated by Django 2.2 on 2021-05-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40, null=True)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('whatsapp_no', models.CharField(max_length=10, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(max_length=40)),
                ('problems', models.CharField(max_length=200)),
                ('consultation_mode', models.CharField(choices=[('A', 'Audio'), ('V', 'Video'), ('C', 'Chat')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('desc', models.CharField(max_length=300)),
                ('featured_pic', models.ImageField(blank=True, null=True, upload_to='blog_pic/BlogFeaturedPic/')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('author_pic', models.ImageField(blank=True, null=True, upload_to='blog_pic/BlogAuthorPic/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=35)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/ProductProfilePic/')),
                ('used_for', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medolx.Order')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medolx.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medolx.Order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medolx.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medolx.Patient'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=35)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=40)),
                ('qualification', models.CharField(max_length=25)),
                ('hospital_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(choices=[('Endocrine Disorders', 'Endocrine Disorders'), ('Dermatologists', 'Dermatologists'), ('Gyneology and Obstetrics', 'Gyneology and Obstetrics'), ('Pain Management', 'Pain Management'), ('Dietitian & Nutritionist', 'Dietitian & Nutritionist'), ('General Physician', 'General Physician'), ('Sexual Discorders', 'Sexual Discorders'), ('Lifestyle Disorders', 'Lifestyle Disorders'), ('Ear Nose Throat Specialist', 'Ear Nose Throat Specialist'), ('PANCHKARMA SPECIALIST', 'PANCHKARMA SPECIALIST'), ('SKIN & COSMETOLOGIST', 'SKIN & COSMETOLOGIST'), ('HAIR CARE & TRICHOLOGY', 'HAIR CARE & TRICHOLOGY'), ('PSYCOLOGIST', 'PSYCOLOGIST'), ('PAEDIATRIC', 'PAEDIATRIC'), ('DIABITIS SPACIAlist', 'DIABITIS SPACIAlist'), ('Covid Care', 'Covid Care')], default='Cardiologist', max_length=50)),
                ('experience', models.CharField(max_length=5)),
                ('consultation_fee', models.CharField(max_length=5)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
