# Generated by Django 2.2 on 2021-05-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0002_auto_20210526_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_mode',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Chat', 'Chat')], max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
    ]
