# Generated by Django 2.2 on 2021-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0003_auto_20210526_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultation_mode',
            field=models.CharField(choices=[('A', 'Audio'), ('V', 'Video'), ('C', 'Chat')], max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
