# Generated by Django 2.2 on 2021-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0005_auto_20210527_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tracker',
            field=models.CharField(choices=[('Consult', 'Consult'), ('Follow_Up', 'Follow Up')], default='Consult', max_length=12),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='consultation_mode',
            field=models.CharField(choices=[('Audio', 'Audio'), ('Video', 'Video'), ('Chat', 'Chat')], max_length=7),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
