# Generated by Django 2.2 on 2021-05-28 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0006_auto_20210528_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tracker',
            field=models.CharField(choices=[('Consult', 'Consult'), ('Follow_Up', 'Follow Up'), ('Complete', 'Complete')], default='Consult', max_length=12),
        ),
    ]
