# Generated by Django 2.2 on 2021-05-28 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0007_auto_20210528_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 5, 28, 15, 8, 38, 194763)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=datetime.datetime(2021, 5, 28, 15, 8, 38, 194790)),
        ),
    ]
