# Generated by Django 2.2 on 2021-05-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0009_auto_20210530_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
