# Generated by Django 4.1.3 on 2023-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0013_auto_20210603_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog_pic/BlogAuthorPic/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog_pic/BlogFeaturedPic/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile_pic/ProductProfilePic/'),
        ),
    ]
