# Generated by Django 4.1.3 on 2023-02-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medolx', '0014_alter_blog_author_pic_alter_blog_featured_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pic/BlogAuthorPic/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='featured_pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog_pic/BlogFeaturedPic/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/ProductProfilePic/'),
        ),
    ]
